resolver: lts-11.1
packages:
- servant-streaming/
- servant-streaming-server/
- servant-streaming-client/
- servant-streaming-docs/
extra-deps:
- streaming-wai-0.1.1
- pipes-http-1.0.5
- git: https://github.com/haskell-servant/servant
  commit: e3158d70168ab0087c867e9f9761d2aff2b01182
  subdirs:
    - servant-server
    - servant
    - servant-client-core
    - servant-client
    - servant-docs
