flags:
  transformers-compat:
    five: true
packages:
- servant-streaming/
- servant-streaming-server/
- servant-streaming-client/
- servant-streaming-docs/
extra-deps:
- aeson-1.4.0.0
- base-compat-0.10.1
- exceptions-0.10.0
- http-api-data-0.3.8.1
- pipes-http-1.0.5
- servant-0.14
- servant-client-0.14
- servant-client-core-0.14
- servant-server-0.14
- streaming-wai-0.1.1
- transformers-base-0.4.5.2
- transformers-compat-0.6.2
resolver: lts-11.15
